language: java
jdk: openjdk10
script:
  - mvn test -B -Dmatsim.preferLocalDtds=true
#  - if [[ $TRAVIS_BRANCH == "releases" && $TRAVIS_PULL_REQUEST = "false" ]]; then if [[ $( cat pom.xml | grep SNAPSHOT ) ]]; then exit 1; else mvn deploy -DskipTests=true --settings=settings.xml; fi; fi
#  - if [[ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST = "false" ]]; then if ! [[ $( cat pom.xml | grep SNAPSHOT ) ]]; then exit 1; else mvn deploy -DskipTests=true --settings=settings.xml; fi; fi
env:
  global:
    - MAVEN_OPTS="-Xmx2g"
cache:
  directories:
  - $HOME/.m2
